### ISSUE TITLE
Prepare release 3.2

### ISSUE THREAD

**Issue by bchretien** [roboptim/roboptim-core#105]
This issue aims at tracking the state of the 3.2 release.

- [x] Prepare `dev` branches
  - [x] Make `Solver` and `Problem` only templated on the matrix type
  - [x] Make `Problem` constructor take a `shared_ptr`. Const ref version kept for backward compatibility (for now...). (cf. 6cafd4cecae07facc59e16480ba17aefa1ef4b18)
  - [x] `roboptim-core` @ `dev` 
  - [x] `roboptim-shared-tests` @ `dev`
  - [x] `roboptim-core-plugin-ipopt` @ `dev`
  - [x] `roboptim-core-plugin-nlopt` @ `dev`
  - [x] `roboptim-trajectory` @ `dev` (cf. roboptim/roboptim-trajectory#35)
  - [x] `roboptim-core-python` @ `dev`
  - [x] `roboptim-core-manifold` @ `dev`
  - [x] `roboptim-capsule` @ `dev`
- [x] Merge `dev` branches to `master`
  - [x] `roboptim-core` @ `master` 
  - [x] `roboptim-shared-tests` @ `master`
  - [x] `roboptim-core-plugin-ipopt` @ `master`
  - [x] `roboptim-core-plugin-nlopt` @ `master`
  - [x] `roboptim-trajectory` @ `master`
  - [x] `roboptim-core-python` @ `master`
  - [x] `roboptim-core-manifold` @ `master`
  - [x] `roboptim-capsule` @ `master`

Follow-up work that will need to be done at some point:

- [x] `roboptim-core-plugin-cminpack`
- [x] `roboptim-core-plugin-eigen`
- [x] `roboptim-core-plugin-knitro` (cf. roboptim/roboptim-core-plugin-knitro#1)
- [x] `roboptim-core-plugin-nag` (cf. roboptim/roboptim-core-plugin-nag#7)

**Comment by bchretien** [comment]
Follow-up work that will need to be done at some point:

- [ ] `roboptim-core-plugin-nag` (cf. roboptim/roboptim-core-plugin-nag#7)
- [ ] `roboptim-core-plugin-knitro` (cf. roboptim/roboptim-core-plugin-knitro#1)

**Comment by bchretien** [comment]
NAG and KNITRO have been updated accordingly, although not released. Still, I'm closing this.
