### ISSUE TITLE
Progress towards 3.0 release for other packages

### ISSUE THREAD

**Issue by bchretien** [roboptim/roboptim-core#84]
This issue aims at tracking progress for our next release:
- [x] [roboptim-core](https://github.com/roboptim/roboptim-core)
  - [x] Prepare new API
  - [x] Enable `3.0` branch [![Build Status](https://travis-ci.org/roboptim/roboptim-core.svg?branch=3.0)](https://travis-ci.org/roboptim/roboptim-core)
- [x] [roboptim-core-plugin-ipopt](https://github.com/roboptim/roboptim-core-plugin-ipopt)
  - [x] Conversion to the new API (cf. roboptim/roboptim-core-plugin-ipopt#26)
  - [x] Optimize thanks to Eigen::Ref (cf. roboptim/roboptim-core-plugin-ipopt#26)
  - [x] Enable `3.0` branch [![Build Status](https://travis-ci.org/roboptim/roboptim-core-plugin-ipopt.svg?branch=3.0)](https://travis-ci.org/roboptim/roboptim-core-plugin-ipopt)
- [x] [roboptim-core-plugin-cminpack](https://github.com/roboptim/roboptim-core-plugin-cminpack)
  - [x] Conversion to the new API (cf. https://github.com/roboptim/roboptim-core-plugin-cminpack/commit/2751720bdd8e0c924db896abc17a85efe2479be5)
  - [x] Enable `3.0` branch [![Build Status](https://travis-ci.org/roboptim/roboptim-core-plugin-cminpack.svg?branch=3.0)](https://travis-ci.org/roboptim/roboptim-core-plugin-cminpack)
- [x] [roboptim-core-plugin-eigen](https://github.com/roboptim/roboptim-core-plugin-eigen)
  - [x] Conversion to the new API (cf. https://github.com/roboptim/roboptim-core-plugin-eigen/commit/f6f2b765c8cd08200bb62e96c473e308b56073da)
  - [x] Enable `3.0` branch [![Build Status](https://travis-ci.org/roboptim/roboptim-core-plugin-eigen.svg?branch=3.0)](https://travis-ci.org/roboptim/roboptim-core-plugin-eigen)
- [x] [roboptim-core-plugin-nag](https://github.com/roboptim/roboptim-core-plugin-nag)
  - [x] Conversion to the new API (cf. https://github.com/roboptim/roboptim-core-plugin-nag/commit/3519752bde88c99b013b4861ab5add0269fb8770)
  - [x] Enable `3.0` branch [![Build Status](https://travis-ci.org/roboptim/roboptim-core-plugin-nag.svg?branch=3.0)](https://travis-ci.org/roboptim/roboptim-core-plugin-nag) (expected to fail because solver requires a license)
- [x] [roboptim-core-plugin-nlopt](https://github.com/roboptim/roboptim-core-plugin-nlopt)
  - [x] Conversion to the new API (cf. https://github.com/roboptim/roboptim-core-plugin-nlopt/commit/083a048842a264b246dcea5c7f67f1099f68fd1a)
  - [x] Enable `3.0` branch [![Build Status](https://travis-ci.org/roboptim/roboptim-core-plugin-nlopt.svg?branch=3.0)](https://travis-ci.org/roboptim/roboptim-core-plugin-nlopt)
- [x] [roboptim-core-plugin-pagmo](https://github.com/roboptim/roboptim-core-plugin-pagmo)
  - [x] Conversion to the new API (cf. https://github.com/roboptim/roboptim-core-plugin-pagmo/commit/2aebf0f492662f720928a15a6e3c83b9b0979867)
  - [x] Enable `3.0` branch [![Build Status](https://travis-ci.org/roboptim/roboptim-core-plugin-pagmo.svg?branch=3.0)](https://travis-ci.org/roboptim/roboptim-core-plugin-pagmo) (expected to fail because of solver's random method)
- [x] [roboptim-core-python](https://github.com/roboptim/roboptim-core-python)
  - [x] Conversion to the new API (cf. https://github.com/roboptim/roboptim-core-python/commit/801f2481bca5f9e8f423359d75353e4bccf4c0e3)
  - [x] Enable `3.0` branch [![Build Status](https://travis-ci.org/roboptim/roboptim-core-python.svg?branch=3.0)](https://travis-ci.org/roboptim/roboptim-core-python)
- [x] [roboptim-trajectory](https://github.com/roboptim/roboptim-trajectory)
  - [x] Conversion to the new API (cf. roboptim/roboptim-trajectory#24)
  - [x] Enable `3.0` branch [![Build Status](https://travis-ci.org/roboptim/roboptim-trajectory.svg?branch=3.0)](https://travis-ci.org/roboptim/roboptim-trajectory)
- [x] [roboptim-shared-tests](https://github.com/roboptim/roboptim-shared-tests)
  - [x] Conversion to the new API (cf. roboptim/roboptim-shared-tests#14)
- [x] ~~[roboptim-retargeting](https://github.com/roboptim/roboptim-retargeting)~~
  - ---> requires private files
- [x] [roboptim-tutorial](https://github.com/roboptim/roboptim-tutorial)
  - [x] Conversion to the new API (cf. https://github.com/roboptim/roboptim-tutorial/commit/1fd261bcce0e77169471a6c85b772763089329c4)
- [x] [roboptim-capsule](https://github.com/roboptim/roboptim-capsule)
  - [x] Conversion to the new API (cf. https://github.com/roboptim/roboptim-capsule/commit/60a6350f56695c40cdc84e5b0cffc74947f8592f)
  - [x] Enable `3.0` branch [![Build Status](https://travis-ci.org/roboptim/roboptim-capsule.svg?branch=3.0)](https://travis-ci.org/roboptim/roboptim-capsule)
- [ ] Benchmark large dense problems for  `Eigen::Ref`
- [x] Rename `filter` subdirectory (cf. #85)

**Comment by bchretien** [comment]
We will still need to do some benchmarking for `Eigen::Ref`, but this can be done after the release.
